import type { Project, ProjectGroup, ProjectGroupListResponse } from "@/types/project";

const MOCK_DELAY_MS = 600;

const EXTRA_PROJECTS: Project[] = [
  {
    project_id: "proj-009",
    name: "React Component Library",
    description:
      "재사용 가능한 React UI 컴포넌트 라이브러리. 스토리북 기반 문서화 및 접근성 자동 분석을 포함합니다.",
    domain: "Frontend",
    product_type: "Library",
    modules: ["requirements", "design"],
    member_count: 7,
    status: "active",
    lifecycle_status: "published",
    analysis_type: "javascript_typescript",
    readiness: null,
    created_at: "2025-07-15T09:00:00Z",
    updated_at: "2026-05-20T10:00:00Z",
  },
  {
    project_id: "proj-010",
    name: "AI Model Inference Server",
    description:
      "실시간 추론을 위한 고성능 Python 서버. GPU 메모리 최적화 및 레이턴시 분석 도구입니다.",
    domain: "AI/ML",
    product_type: "Web Service",
    modules: ["requirements", "design", "testcase"],
    member_count: 12,
    status: "active",
    lifecycle_status: "published",
    analysis_type: "python",
    readiness: null,
    created_at: "2025-09-01T08:00:00Z",
    updated_at: "2026-05-22T14:00:00Z",
  },
  {
    project_id: "proj-011",
    name: "Spring Microservices Framework",
    description:
      "Spring Boot 기반 마이크로서비스 프레임워크. 서비스 간 종속성 분석 및 API 호환성 검증을 제공합니다.",
    domain: "Enterprise",
    product_type: "Framework",
    modules: ["requirements", "design"],
    member_count: 9,
    status: "active",
    lifecycle_status: "published",
    analysis_type: "java",
    readiness: null,
    created_at: "2025-04-10T11:00:00Z",
    updated_at: "2026-05-19T09:30:00Z",
  },
  {
    project_id: "proj-012",
    name: "Embedded RTOS Analyzer",
    description:
      "실시간 운영체제 커널 코드의 메모리 누수 및 데드락 가능성을 정적 분석합니다.",
    domain: "Embedded Systems",
    product_type: "CLI Tool",
    modules: ["requirements", "testcase"],
    member_count: 5,
    status: "active",
    lifecycle_status: "published",
    analysis_type: "c_cpp",
    readiness: null,
    created_at: "2025-11-20T13:00:00Z",
    updated_at: "2026-05-18T16:00:00Z",
  },
  {
    project_id: "proj-013",
    name: "SwiftUI Design System",
    description:
      "iOS 앱을 위한 SwiftUI 기반 디자인 시스템. 컴포넌트 사용 패턴 분석 및 일관성 검증을 수행합니다.",
    domain: "Mobile",
    product_type: "iOS Framework",
    modules: ["design", "testcase"],
    member_count: 4,
    status: "active",
    lifecycle_status: "draft",
    analysis_type: "swift",
    readiness: null,
    created_at: "2026-03-01T07:00:00Z",
    updated_at: "2026-05-21T11:00:00Z",
  },
  {
    project_id: "proj-014",
    name: "Flutter Cross-Platform Toolkit",
    description:
      "Flutter 기반 크로스 플랫폼 개발 툴킷. 위젯 트리 분석 및 퍼포먼스 프로파일링을 지원합니다.",
    domain: "Mobile",
    product_type: "Flutter Plugin",
    modules: ["requirements"],
    member_count: 4,
    status: "active",
    lifecycle_status: "draft",
    analysis_type: "dart",
    readiness: null,
    created_at: "2026-02-01T09:00:00Z",
    updated_at: "2026-05-14T13:00:00Z",
  },
  {
    project_id: "proj-015",
    name: "webOS Media Pipeline",
    description:
      "webOS 스마트 TV의 미디어 재생 파이프라인 분석. 코덱 호환성 및 스트리밍 성능을 측정합니다.",
    domain: "Smart TV",
    product_type: "TV App",
    modules: ["design", "testcase"],
    member_count: 6,
    status: "active",
    lifecycle_status: "published",
    analysis_type: "webos",
    readiness: null,
    created_at: "2025-08-05T10:00:00Z",
    updated_at: "2026-04-15T08:00:00Z",
  },
  {
    project_id: "proj-016",
    name: "Legacy C++ Refactoring Tool",
    description:
      "대규모 레거시 C++ 코드베이스의 리팩토링을 지원하는 정적 분석 도구. 의존성 그래프 시각화를 포함합니다.",
    domain: "Systems",
    product_type: "Desktop App",
    modules: ["requirements", "design"],
    member_count: 8,
    status: "active",
    lifecycle_status: "published",
    analysis_type: "objective_c_cpp",
    readiness: null,
    created_at: "2025-06-20T08:00:00Z",
    updated_at: "2026-05-16T12:00:00Z",
  },
  {
    project_id: "proj-017",
    name: "TypeScript AST Analyzer",
    description:
      "TypeScript AST 기반 코드 품질 분석기. 커스텀 린트 규칙 생성 및 타입 추론 검증을 제공합니다.",
    domain: "Developer Tools",
    product_type: "CLI Tool",
    modules: ["requirements", "testcase"],
    member_count: 5,
    status: "active",
    lifecycle_status: "published",
    analysis_type: "javascript_typescript",
    readiness: null,
    created_at: "2025-10-01T09:00:00Z",
    updated_at: "2026-05-25T07:00:00Z",
  },
  {
    project_id: "proj-018",
    name: "Data Science Notebook Analyzer",
    description:
      "Jupyter Notebook 기반 데이터 과학 워크플로우의 품질 분석. 셀 간 의존성 및 재현성 검증을 수행합니다.",
    domain: "Data Science",
    product_type: "Plugin",
    modules: ["requirements"],
    member_count: 3,
    status: "active",
    lifecycle_status: "draft",
    analysis_type: "python",
    readiness: null,
    created_at: "2026-04-10T11:00:00Z",
    updated_at: "2026-05-22T15:00:00Z",
  },
  {
    project_id: "proj-019",
    name: "Java Batch Processor",
    description:
      "대용량 배치 처리 시스템의 코드 품질 분석. 병렬 처리 최적화 및 리소스 사용량 측정 도구입니다.",
    domain: "Enterprise",
    product_type: "Web Service",
    modules: ["requirements", "design", "testcase"],
    member_count: 7,
    status: "active",
    lifecycle_status: "draft",
    analysis_type: "java",
    readiness: null,
    created_at: "2026-01-15T08:00:00Z",
    updated_at: "2026-05-23T10:00:00Z",
  },
  {
    project_id: "proj-020",
    name: "C++ Game Engine Profiler",
    description:
      "게임 엔진의 C++ 코드베이스 프로파일링 도구. 프레임 단위 성능 분석 및 메모리 할당 추적을 지원합니다.",
    domain: "Game Development",
    product_type: "Desktop App",
    modules: ["requirements", "design"],
    member_count: 6,
    status: "active",
    lifecycle_status: "published",
    analysis_type: "c_cpp",
    readiness: null,
    created_at: "2025-05-10T07:00:00Z",
    updated_at: "2026-05-17T13:00:00Z",
  },
  {
    project_id: "proj-021",
    name: "Swift Package Validator",
    description:
      "Swift Package Manager 기반 패키지의 API 호환성 및 의존성 충돌을 사전에 검증하는 도구입니다.",
    domain: "Mobile",
    product_type: "CLI Tool",
    modules: ["testcase"],
    member_count: 2,
    status: "active",
    lifecycle_status: "deleted",
    analysis_type: "swift",
    readiness: null,
    created_at: "2025-12-01T10:00:00Z",
    updated_at: "2026-02-20T09:00:00Z",
  },
  {
    project_id: "proj-022",
    name: "Dart Backend Framework",
    description:
      "Dart 언어로 작성된 경량 백엔드 프레임워크. 서버 사이드 코드의 정적 분석 및 API 문서 자동 생성 기능을 제공합니다.",
    domain: "Backend",
    product_type: "Framework",
    modules: ["requirements", "design"],
    member_count: 4,
    status: "active",
    lifecycle_status: "draft",
    analysis_type: "dart",
    readiness: null,
    created_at: "2026-03-20T08:00:00Z",
    updated_at: "2026-05-24T16:00:00Z",
  },
  {
    project_id: "proj-023",
    name: "Objective-C Bridge Analyzer",
    description:
      "Objective-C와 Swift 간 브릿지 코드의 타입 안전성 및 메모리 관리 패턴을 분석합니다.",
    domain: "Mobile",
    product_type: "CLI Tool",
    modules: ["requirements"],
    member_count: 3,
    status: "active",
    lifecycle_status: "deleted",
    analysis_type: "objective_c_cpp",
    readiness: null,
    created_at: "2025-09-15T09:00:00Z",
    updated_at: "2026-01-10T11:00:00Z",
  },
];

const MOCK_GROUPS: ProjectGroupListResponse = {
  groups: [
    {
      group_id: "group-001",
      name: "AI & Web Platform",
      description:
        "인공지능 및 차세대 엔터프라이즈 웹 핵심 솔루션들을 개발하고 코드 아키텍처를 정밀 정적 분석하는 프로젝트 그룹입니다.",
      project_count: 3,
      manager_count: 3,
      member_count: 24,
      created_at: "2025-06-01T09:00:00Z",
      updated_at: "2026-05-21T08:00:00Z",
      projects: [
        {
          project_id: "proj-001",
          name: "AISE+ Web Application",
          description:
            "차세대 AI 기반 소프트웨어 공학 분석 플랫폼. 요구사항 분석부터 설계, 테스트케이스 생성까지 전 과정을 자동화합니다.",
          domain: "Software Engineering",
          product_type: "Web Application",
          modules: ["requirements", "design", "testcase"],
          member_count: 8,
          status: "active",
          lifecycle_status: "published",
          analysis_type: "javascript_typescript",
          readiness: null,
          created_at: "2025-12-01T09:00:00Z",
          updated_at: "2026-05-18T14:30:00Z",
        },
        {
          project_id: "proj-004",
          name: "Python ML Pipeline",
          description:
            "머신러닝 모델 학습 파이프라인의 정적 분석 및 테스트 커버리지 자동 측정 시스템입니다.",
          domain: "AI/ML",
          product_type: "Library",
          modules: ["requirements", "testcase"],
          member_count: 6,
          status: "active",
          lifecycle_status: "published",
          analysis_type: "python",
          readiness: null,
          created_at: "2025-10-05T11:30:00Z",
          updated_at: "2026-05-19T16:45:00Z",
        },
        {
          project_id: "proj-008",
          name: "Java Enterprise Analyzer",
          description:
            "Spring Boot 기반 엔터프라이즈 애플리케이션의 아키텍처 분석과 코드 품질 측정 도구입니다.",
          domain: "Enterprise",
          product_type: "Web Service",
          modules: ["requirements", "design", "testcase"],
          member_count: 10,
          status: "active",
          lifecycle_status: "published",
          analysis_type: "java",
          readiness: null,
          created_at: "2025-06-01T09:00:00Z",
          updated_at: "2026-05-21T08:00:00Z",
        },
      ],
    },
    {
      group_id: "group-002",
      name: "Mobile & Frontend Platform",
      description:
        "모바일 어플리케이션의 CI/CD 빌드 최적화 및 레거시 모바일 코드베이스의 Swift 마이그레이션 계획을 추진하는 그룹입니다.",
      project_count: 3,
      manager_count: 2,
      member_count: 10,
      created_at: "2025-08-20T10:00:00Z",
      updated_at: "2026-05-20T09:00:00Z",
      projects: [
        {
          project_id: "proj-003",
          name: "iOS CI/CD Pipeline",
          description:
            "Swift 기반 iOS 앱의 CI/CD 파이프라인 구축 및 코드 품질 자동 분석.",
          domain: "Mobile",
          product_type: "iOS App",
          modules: ["design"],
          member_count: 5,
          status: "archived",
          lifecycle_status: "deleted",
          analysis_type: "swift",
          readiness: null,
          created_at: "2025-08-20T10:00:00Z",
          updated_at: "2026-03-01T07:00:00Z",
        },
        {
          project_id: "proj-006",
          name: "Legacy Objective-C Migration",
          description:
            "레거시 Objective-C 코드베이스를 분석하여 Swift로의 점진적 마이그레이션 계획을 수립합니다.",
          domain: "Mobile",
          product_type: "iOS App",
          modules: ["requirements"],
          member_count: 2,
          status: "active",
          lifecycle_status: "published",
          analysis_type: "objective_c_cpp",
          readiness: null,
          created_at: "2026-02-14T13:00:00Z",
          updated_at: "2026-05-15T10:20:00Z",
        },
        {
          project_id: "proj-007",
          name: "Dart Flutter Plugin",
          description:
            "Flutter 플러그인의 코드 품질을 정적 분석하고 API 호환성 리포트를 생성합니다.",
          domain: "Mobile",
          product_type: "Flutter Plugin",
          modules: ["testcase"],
          member_count: 3,
          status: "active",
          lifecycle_status: "draft",
          analysis_type: "dart",
          readiness: null,
          created_at: "2026-04-01T08:00:00Z",
          updated_at: "2026-05-20T09:00:00Z",
        },
      ],
    },
    {
      group_id: "group-003",
      name: "Embedded & TV Systems",
      description:
        "LG webOS 스마트 TV 제품군 탑재 앱 및 임베디드 펌웨어 취약점, 메모리 정밀 정적 분석 솔루션 모음입니다.",
      project_count: 2,
      manager_count: 2,
      member_count: 7,
      created_at: "2025-11-15T08:00:00Z",
      updated_at: "2026-04-28T11:00:00Z",
      projects: [
        {
          project_id: "proj-002",
          name: "Embedded Firmware Analyzer",
          description:
            "임베디드 시스템의 펌웨어를 정적 분석하고 취약점과 품질 지표를 리포트로 제공하는 도구입니다.",
          domain: "Embedded Systems",
          product_type: "CLI Tool",
          modules: ["requirements"],
          member_count: 4,
          status: "active",
          lifecycle_status: "draft",
          analysis_type: "c_cpp",
          readiness: null,
          created_at: "2025-11-15T08:00:00Z",
          updated_at: "2026-05-10T09:15:00Z",
        },
        {
          project_id: "proj-005",
          name: "webOS TV App Suite",
          description:
            "LG webOS 스마트 TV용 애플리케이션 스위트. 성능 분석과 메모리 누수 탐지 기능을 포함합니다.",
          domain: "Smart TV",
          product_type: "TV App",
          modules: ["design", "testcase"],
          member_count: 3,
          status: "active",
          lifecycle_status: "draft",
          analysis_type: "webos",
          readiness: null,
          created_at: "2026-01-10T07:00:00Z",
          updated_at: "2026-04-28T11:00:00Z",
        },
      ],
    },
    {
      group_id: "group-004",
      name: "Enterprise Solutions Suite",
      description:
        "엔터프라이즈 환경의 코드 품질 관리와 분석 자동화를 위한 통합 솔루션 그룹입니다. 다양한 언어와 플랫폼을 아우르는 15개 프로젝트로 구성되어 있습니다.",
      project_count: 15,
      manager_count: 4,
      member_count: 82,
      created_at: "2025-04-01T09:00:00Z",
      updated_at: "2026-05-25T18:00:00Z",
      projects: EXTRA_PROJECTS,
    },
  ],
};

export const projectGroupService = {
  list: (): Promise<ProjectGroupListResponse> =>
    new Promise((resolve) => {
      setTimeout(() => resolve(MOCK_GROUPS), MOCK_DELAY_MS);
    }),

  get: (id: string): Promise<ProjectGroup> =>
    new Promise((resolve, reject) => {
      setTimeout(() => {
        const group = MOCK_GROUPS.groups.find((g) => g.group_id === id);
        if (group) {
          resolve(group);
        } else {
          reject(new Error(`프로젝트 그룹을 찾을 수 없습니다: ${id}`));
        }
      }, 400);
    }),
};
